### ISSUE TITLE
The ability to disable notifications about the inability to connect to the server

### ISSUE THREAD

**Issue by MartinJDavis93** [Clemens-E/obsidian-languagetool-plugin#113] opened 2023-11-22 12:05 UTC
Thank you very much for the excellent plugin. Since I often use Obsidian in places where I cannot connect to the internet, constant notifications that it's unable to connect to the server make it difficult to work smoothly. Therefore, I have to disable the plugin each time, which is not convenient at all. I understand that it's possible to enable manual spell-check instead of automatic, but in cases where there is an internet connection, automatic spell-check is much more convenient. It would be great if you could add an option in the plugin settings to disable notifications about the inability to connect to the server (with all the appropriate warnings). Even better, if you could limit such notifications to one per session (while the program is open), although I understand that this might be more challenging to implement. If it's not possible to choose which type of notifications to display and which not to, there might even be a switch to disable all notification types at the user's risk. This would still be better than constant cyclic notifications. I hope you will consider my request. Once again, thank you for the excellent extension. Have a great day!

**Comment by Clemens-E** [comment] 2023-12-12 22:37
Thanks to @brandones and his PR #109 this should be fixed.
The Plugin will only display one notification if a request fails, and if the cause or status didn't change, it will not show further notifications until the status changes

**Closed by Clemens-E** 2023-12-12 22:37 UTC

**Comment by MartinJDavis93** [comment] 2023-12-14 08:19
> Thanks to @brandones and his PR #109 this should be fixed. The Plugin will only display one notification if a request fails, and if the cause or status didn't change, it will not show further notifications until the status changes

Yes, it works, thanks for this ❤️ However, there is one not very pleasant nuance: the notification doesn't close automatically. You need to click on it to close. I'd greatly appreciate it if you could fix this.

**Comment by brandones** [comment] 2023-12-16 14:00
My thought in making it stay open was that since it doesn't come up multiple times it would be important to make sure the user actually sees it when it does come up, rather than e.g. if they look away for 10 seconds, and then their auto-correct doesn't work, and they don't know why. But your preference is also understandable. Maybe it would make a good setting.

**Comment by MartinJDavis93** [comment] 2023-12-16 14:45
> My thought in making it stay open was that since it doesn't come up multiple times it would be important to make sure the user actually sees it when it does come up, rather than e.g. if they look away for 10 seconds, and then their auto-correct doesn't work, and they don't know why. But your preference is also understandable. Maybe it would make a good setting.

Certainly, everyone has their own use case. Therefore, making this setting a separate parameter would probably be the most optimal option for everyone.
