### ISSUE TITLE
Disable LT for specific notes.

### ISSUE THREAD

**Issue by thibaultmol** [Clemens-E/obsidian-languagetool-plugin#104] opened 2023-08-07 19:53 UTC
(I understand the project is in maintenance mode)
It would be nice if you could maybe put something in the frontmatter of a note to make it so that the plugin doesn't send your text to LT.
I don't care about most text, but daily diaries would ideally stay locally. (and I can't be bothered with the local server. Plus I pay for premium)

**Comment by brandones** [comment] 2023-11-03 15:47
Duplicate of #64

**Comment by Clemens-E** [comment] 2024-02-18 15:34
You can add the tag `lt-ignore`, and the plugin will skip any checks (even manual ones)

**Closed by Clemens-E** 2024-02-18 15:34 UTC
